[package]
name = "wmd"
version = "0.2.2"
edition = "2021"
publish = false
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1"
argh = "0.1"
async-trait = "0.1"
indoc = "1"
itertools = "0.10"
serde = { version = "1", features = ["derive"] }
thiserror = "1"
tokio = { version = "1", features = ["full"] }
toml = "0.5"
tracing = { version = "0.1", features = ["release_max_level_info"] }
tracing-subscriber = "0.2"
url = { version = "2", features = ["serde"] }
warp = "0.3"

[dev-dependencies]
assert_cmd = "2"
pretty_assertions = "0.7"
rand = "0.8"
reqwest = "0.11"
tempfile = "3"
