app = "wmd"

[build]
image = "registry.fly.io/wmd:edge"

[[services]]
internal_port = 80
protocol = "tcp"

[[services.ports]]
handlers = ["http"]
port = 80

[[services.ports]]
handlers = ["tls", "http"]
port = 443

[[services.http_checks]]
interval = "5s"
grace_period = "10s"
method = "get"
path = "/"
protocol = "http"
timeout = "1s"
