# used to generate open search description
url = "http://127.0.0.1:39496/"

[[targets]]
prefix = "rs"
name = "The Rust Standard Library"
url_template = "https://doc.rust-lang.org/std/index.html?search={keywords}"

[[targets]]
prefix = "drx"
name = "Docs.rs (direct)"
# `keywords` will be replaced by the actual keywords
url_template = "https://docs.rs/{keywords}"
