name: wmd
version: 0.0.0.0
github: "kafji/wmd"
author: "Kafji"
maintainer: "k@kafji.net"
copyright: "2022 Kafji"

extra-source-files:
  - README.md

dependencies:
  - base
  - blaze-html
  - bytestring
  - containers
  - either
  - fmt
  - htoml-megaparsec
  - lens
  - megaparsec
  - mtl
  - optparse-applicative
  - scotty
  - tagsoup
  - text
  - text-show
  - transformers
  - unordered-containers
  - vector
  - wai-extra

default-extensions:
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleContexts
  - LambdaCase
  - ImportQualifiedPost
  - NoStarIsType
  - OverloadedRecordDot
  - OverloadedStrings
  - QuasiQuotes
  - RecordWildCards
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications

language: GHC2021

library:
  source-dirs: src

executables:
  wmd-app:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wmd
    when:
      - condition: false
        other-modules: Paths_wmd

tests:
  wmd-test:
    main: Main.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wmd
      - tasty
      - tasty-golden
      - tasty-golden-easy
      - tasty-hunit
      - tasty-quickcheck
