name: wmd
version: 0.0.0.0
github: "kafji/wmd"
author: "Kafji"
maintainer: "k@kafji.net"
copyright: "2022 Kafji"

extra-source-files:
  - README.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/kafji/wmd#readme>

dependencies:
  - base >= 4.7 && < 5
  - blaze-html
  - containers
  - htoml-megaparsec
  - htoml-parse
  - lens
  - megaparsec
  - mtl
  - scotty
  - tagsoup
  - text
  - unordered-containers
  - vector
  - wai-extra

default-extensions:
  - BangPatterns
  - BlockArguments
  - DeriveAnyClass
  - DeriveGeneric
  - FlexibleContexts
  - LambdaCase
  - ImportQualifiedPost
  - NoStarIsType
  - OverloadedStrings
  - QuasiQuotes
  - ScopedTypeVariables
  - TemplateHaskell
  - TypeApplications

language: GHC2021

library:
  source-dirs: src

executables:
  wmd-hs-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wmd
    when:
      - condition: false
        other-modules: Paths_wmd

tests:
  wmd-test:
    main: Test.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - wmd
      - tasty
      - tasty-hunit
      - tasty-quickcheck
      - tasty-hedgehog
