# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      RUST_BACKTRACE: full
      RUST_LOG: debug
    steps:
      - uses: actions/checkout@v2

      - name: Restore Cargo cache
        uses: actions/cache@v2
        with:
          # https://doc.rust-lang.org/cargo/guide/cargo-home.html#caching-the-cargo-home-in-ci
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: cargo-${{ runner.os }}-${{ hashFiles('./Cargo.toml', './Cargo.lock') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Test
        run: cargo test

      - name: Build
        run: cargo build --release

      - uses: docker/setup-buildx-action@v1

      - uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/kafji/wmd
          tags: |
            type=edge
            type=sha,prefix=rev-
            type=ref,event=branch
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=registry,ref=ghcr.io/kafji/wmd:buildcache
          cache-to: type=registry,ref=ghcr.io/kafji/wmd:buildcache,mode=max
